### ISSUE TITLE
Exact sided distance

### ISSUE THREAD

**Issue by parrotdance** [marcoscavaleiro/iSimpleRadar#2]
Hi, I'm a new player of iRacing and played GT series before, and I really want a radar works like GT does, but I never found that. It seems like all of third-party iRacing overlays are not provide radar with exact sided distance.

I spent a night to do some search and found that the telemetry data source did not provide any helpful data for this purpose. Finally, I found this repo from iRacing forum. Not surprised, only "left side" or "right side" notification, instead of relative position between cars.

Maybe, the precise position data of the vehicle on the track is considered that could be used for illegal purposes?

**Comment by marcoscavaleiro** [comment]
Hi @parrotdance, the iracing telemetry does not provide GPS position to calculate lateral distance or even the lateral distance.. the only information we have is a flag with 3 value, LeftCar, RightCar and LeftRightCar so we are not able to show the lateral distance.

I think the reason is that.. used for illegal purposes..
thanks
